[theme]
primaryColor = "#6366F1"
backgroundColor = "#09090B"
secondaryBackgroundColor = "#0F0F12"
textColor = "#FAFAFA"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = false
showSidebarNavigation = false

[server]
enableCORS = false
enableXsrfProtection = true
